### ISSUE TITLE
Add dislikes view for comments

### ISSUE THREAD

**Issue by emklutse** [KibbeWater/YoutubeDislikes#1]
The app works sometimes, not all the time. Adding functionality for comments will be great.

**Comment by KibbeWater** [comment]
Unfortunately there is no support for dislikes on comments through the API so putting dislikes on them would not be possible.

Is there any repeatable way you have gotten dislikes to not show?

**Comment by emklutse** [comment]
I’m not able to replicate it repeatedly. Sometimes upon initial launch, the dislikes on the video show. Sometimes it doesn’t. On Sep 4, 2024, at 9:56 AM, Snow ***@***.***> wrote:﻿
Unfortunately there is no support for dislikes on comments through the API so putting dislikes on them would not be possible.
Is there any repeatable way you have gotten dislikes to not show?

**Comment by KibbeWater** [comment]
This issue will be closed for now. I am actively monitoring for bugs and addressing them as I discover them. If you identify any reproducible bugs, please reopen the issue, and I will prioritize fixing it as soon as possible.

Thank you!
