### ISSUE TITLE
Latest update broke YouTube shorts

### ISSUE THREAD

**Issue by ya519** [KibbeWater/YoutubeDislikes#3]
Simple, when the extension is enabled, YouTube shorts won't work, when it's disabled, Youtube shorts will work.

**Comment by KibbeWater** [comment]
I will have this looked at ASAP, I should be able to get a patch out by tomorrow or so, for now though you will have to disable the extension though.

**Comment by KibbeWater** [comment]
I'm pushing the update to AppStore, will have to wait for app review which should be finished within 24hr.

Thank you for notifying me!
