### ISSUE TITLE
its bugging

### ISSUE THREAD

**Issue by bumpagram** [KibbeWater/YoutubeDislikes#5]
Good side - looks like its Safari-cross platform.

Bad side -  you can see dislikes only once. Then, you go no another YouTube video and dislikes are gone.  Delete-install again don’t work. Restart Safari - don’t help.  Once helping- restart your Mac. Bullshit.  
And another 2 things - maybe «round» amount of dislikes. So if video has 35,791 dislikes it’s better to show as 35.7K.
and in cause of that - webpage likes/dislikes meter is clipping(too much to show)

I appreciate dev work, but looks like you need to test this before deploy to Appstore.
Please fix this and I ll be happy to by again, but for now I have to ask for refund, it worked just a few hours :(

**Comment by KibbeWater** [comment]
Hey, I appreciate the feedback and I'll look into fixing and improving things. There are plans for a settings page to manage preferences like rounding options etc.. For now it kinda varies depending on users os/browsers locale and language options

Regarding the non-working dislike counter, if it disappears when navigating the site I will absolutely investigate and find the cause, could you please describe what you are doing when this happens, are you able to replicate it or does it appear randomly?

However, there is currently an outage from the API I'm using so you will unfortunately not be able to see dislikes on any videos until the maintainer of that API brings it back up. It should hopefully be up again within 24 hours!

Again, thanks for your feedback!

**Comment by bumpagram** [comment]
interesting.  I tried 3 apps in store today and none are working.

Maybe you should check API, or something.  Or add a few API to jump between them, if google trying to shut it down. 
I've already saw this  "Google war" between AD-blockers/ custom App clients like Vanced/ closing API's and etc

**Comment by KibbeWater** [comment]
There has been a fixed bug which caused dislikes not to be shown. If you are still experiencing this issue on version 1.2.3 (still unreleased on App Store ATM), please notify me!
