### ISSUE TITLE
Dislikes not showing

### ISSUE THREAD

**Issue by ya519** [KibbeWater/YoutubeDislikes#7]
Well, dislikes are not showing, update needed I suppose.

**Comment by KibbeWater** [comment]
I will be looking into it, seems to be fixed on iOS on latest builds (not published on App Store yet). However still broken on macOS. Will be looking more into it and hopefully have a fix by end of week

**Comment by KibbeWater** [comment]
YouTube had changed a single uppercase letter to lowercase causing it to stop working on macOS

It has been fixed in the latest commit

**Comment by ya519** [comment]
> YouTube had changed a single uppercase letter to lowercase causing it to stop working on macOS
> 
> It has been fixed in the latest commit

When will the update come?

**Comment by KibbeWater** [comment]
likely within 24-48 hours
